### PR TITLE
Add usage and examples for bpf_get_stackid helper

### PR DESCRIPTION
**Pull request by maxgio92**
This PR adds usage and examples for the `bpf_get_stackid` helper function to retrieve the kernel or user stack id.

It further links to the more complete official Linux examples of `trace_event` and `offwaketime`.

### CODE REVIEW

**Comment by maxgio92** [comment]
I tested the HTML output and it seems pretty good :-)

**Review by dylandreimerink — CHANGES_REQUESTED** [review]
Awesome! Thanks for the contribution. One request though, could you add the [copyright banner](https://github.com/torvalds/linux/blob/e8f897f4afef0031fe618a8e94127a0934896aba/samples/bpf/offwaketime.bpf.c#L1-L6) to the C snippit? That is a requirement of the original license when copying.

**Review by dylandreimerink — APPROVED** [review]
Nevermind, I thought the snippit was from one of the sited links, but its seems like your original work. Sorry for the noise.

**Comment by maxgio92** [comment]
No problem @dylandreimerink, thank you!

**Pull request merged**
